name: Auto-Update Submodule References

on:
  push:
    repositories:
      - manishraj27/FusionHub-BACKEND-APIGateway
      - manishraj27/FusionHub-BACKEND-AdminService
      - manishraj27/FusionHub-BACKEND-StudentService
      - manishraj27/FusionHub-BACKEND-EurekaServer
      - manishraj27/FusionHub-FRONTEND

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository, including submodules
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}  # Use the PAT to authenticate

      # Step 2: Update all submodules to the latest commit
      - name: Update Submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Auto-updated submodule references to latest commits"
          git push
