name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git pull origin $(git rev-parse --abbrev-ref HEAD)'
          git add .
          git commit -m "Update submodule references" || echo "No changes to commit"
          git push
