name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive

      - name: Configure Git for Authentication
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Update Submodules to Latest Commit
        run: |
          git submodule foreach --recursive 'git pull origin $(git rev-parse --abbrev-ref HEAD)'
          git add .
          git commit -m "Update submodule references" || echo "No changes to commit"
          git push
