name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}  # Use the PAT for authentication

      - name: Update Submodules to Latest Commit
        run: |
          git submodule foreach 'git pull origin $(git rev-parse --abbrev-ref HEAD)'
          git add .
          git commit -m "Update submodule references"
          git push
